name: shikha
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8



  #utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  dio: ^5.1.1

  url_launcher: ^6.1.7
  connectivity_plus: ^2.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0


  #state managemnt
  get: ^4.6.6
  get_storage: ^2.1.1
  path_provider: ^2.0.10
  permission_handler: ^10.2.0
  external_path: ^2.0.1
  open_file: ^3.5.7
  flutter_pdfview: ^1.0.0
  syncfusion_flutter_pdfviewer: ^27.1.48
  shared_preferences: ^2.0.9
  provider: ^6.0.0
  flutter_rating_bar: ^4.0.0








  #product:










dev_dependencies:
  flutter_launcher_icons: ^0.14.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/book.jpg"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/book.jpg"

  windows:
    generate: true
    image_path: "assets/logos/book.jpg"
    icon_size: 48




  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:


    - assets/logos/

    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/on_boarding_images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        