// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5wtJ5P8OA8-1ql2DWWv3u8yBOg_6UHw',
    appId: '1:90478953357:web:82f89d284b58949bf473c4',
    messagingSenderId: '90478953357',
    projectId: 'bookhivee',
    authDomain: 'bookhivee.firebaseapp.com',
    storageBucket: 'bookhivee.appspot.com',
    measurementId: 'G-92YK6R9Z2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBQs0BByHm8Wj3BGDncdjxKndyyldLnLM',
    appId: '1:90478953357:android:295f4079167778daf473c4',
    messagingSenderId: '90478953357',
    projectId: 'bookhivee',
    storageBucket: 'bookhivee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFQbdOGxDJL9tcxRRm1WpvcfKLyUzOx4',
    appId: '1:90478953357:ios:8cc8bbdc0a146768f473c4',
    messagingSenderId: '90478953357',
    projectId: 'bookhivee',
    storageBucket: 'bookhivee.appspot.com',
    androidClientId: '90478953357-d4k7mmtugrbo3ct6l0p9o4sgmn0i6k16.apps.googleusercontent.com',
    iosClientId: '90478953357-eki29d7ntbbr4icpqduqbnirpaq7iq8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.shikha',
  );

}